### ISSUE TITLE
Минификация классов в production

### ISSUE THREAD

**Issue by kusa-work** [alfa-laboratory/arui-presets#251]
Не смог найти в процессе сборки код отвечающий за подобную минификацию классов: https://drive.google.com/uc?id=1Q4yM8zayuq5TLMtxs3jFLLPqG-3DjtfH
Подскажите пожалуйста, как это достигается
Не возникает потом проблем с отладкой?

**Comment by YozhEzhi** [comment]
На приведенном скриншоте выше показана не минификация, а результат работы [css-модулей](https://github.com/css-modules/css-modules).
