### ISSUE TITLE
Не включен array includes

### ISSUE THREAD

**Issue by Luchanso** [alfa-laboratory/arui-presets#65]
Не хватает полифила array.includes, приходиться дополнительно подключать `babel-plugin-array-includes`

**Comment by artptr** [comment]
Если includes используется конкретно в вашем приложении, то, кажется, в него и нужно добавлять. Или includes используется в arui-feather?

**Comment by Luchanso** [comment]
@artptr, он используется конкретно в нашем проекте, если так и задумано, то тогда можно закрывать этот ишью.

**Comment by artptr** [comment]
Ну да, так и задумано. Иначе это можно весь [core-js](https://github.com/zloirock/core-js/blob/master/shim.js) и кучу полифиллов для DOM "заранее" подключить. Получится слишком жирно, а пользы никакой.
